import { CSGOCase } from '../../../../types';

export const diamondSkinsCase: CSGOCase = {
  id: 'diamond-skins',
  name: 'Diamond Skins',
  price: 194.93,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250731/809531025095938048.png',
  category: 'Creators',
  items: [
    {
      id: 'ds-awp-dragonlore',
      weapon: 'AWP',
      skin: 'Dragon Lore',
      rarity: 'Covert',
      condition: 'BS',
      statTrak: false,
      price: 10231.73,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgRHJhZ29uIExvcmUgKEJhdHRsZS1TY2FycmVkKQ==.png',
      odds: 0.050,
    },
    {
      id: 'ds-m4a4-howl',
      weapon: 'M4A4',
      skin: 'Howl',
      rarity: 'Contraband',
      condition: 'FT',
      statTrak: false,
      price: 6871.63,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IEhvd2wgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 0.100,
    },
    {
      id: 'ds-gloves-pandora',
      weapon: '★ Sport Gloves',
      skin: "Pandora's Box",
      rarity: 'Extraordinary',
      condition: 'BS',
      statTrak: false,
      price: 5509.37,
      imageUrl: "https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IFBhbmRvcmEncyBCb3ggKEJhdHRsZS1TY2FycmVkKQ==.png",
      odds: 0.110,
    },
    {
      id: 'ds-gloves-hedge',
      weapon: '★ Sport Gloves',
      skin: 'Hedge Maze',
      rarity: 'Extraordinary',
      condition: 'BS',
      statTrak: false,
      price: 5375.05,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IEhlZGdlIE1hemUgKEJhdHRsZS1TY2FycmVkKQ==.png',
      odds: 0.110,
    },
    {
      id: 'ds-m4a1s-hotrod',
      weapon: 'M4A1-S',
      skin: 'Hot Rod',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 3458.30,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgSG90IFJvZCAoRmFjdG9yeSBOZXcp.png',
      odds: 0.130,
    },
    {
      id: 'ds-awp-medusa',
      weapon: 'AWP',
      skin: 'Medusa',
      rarity: 'Covert',
      condition: 'FT',
      statTrak: false,
      price: 3161.44,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgTWVkdXNhIChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.130,
    },
    {
      id: 'ds-st-karambit-fade',
      weapon: '★ Karambit',
      skin: 'Fade',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: true,
      price: 5004.04,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFN0YXRUcmFr4oSiIEthcmFtYml0IHwgRmFkZSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.220,
    },
    {
      id: 'ds-glock-fade',
      weapon: 'Glock-18',
      skin: 'Fade',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 2517.06,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/R2xvY2stMTggfCBGYWRlIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.250,
    },
    {
      id: 'ds-m9-tiger',
      weapon: '★ M9 Bayonet',
      skin: 'Tiger Tooth',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 1847.69,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE05IEJheW9uZXQgfCBUaWdlciBUb290aCAoRmFjdG9yeSBOZXcp.png',
      odds: 0.300,
    },
    {
      id: 'ds-karambit-lore',
      weapon: '★ Karambit',
      skin: 'Lore',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 1545.02,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEthcmFtYml0IHwgTG9yZSAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.330,
    },
    {
      id: 'ds-m4a4-poseidon',
      weapon: 'M4A4',
      skin: 'Poseidon',
      rarity: 'Classified',
      condition: 'MW',
      statTrak: false,
      price: 1674.15,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IFBvc2VpZG9uIChNaW5pbWFsIFdlYXIp.png',
      odds: 0.360,
    },
    {
      id: 'ds-talon-marble',
      weapon: '★ Talon Knife',
      skin: 'Marble Fade',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 1441.18,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFRhbG9uIEtuaWZlIHwgTWFyYmxlIEZhZGUgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.500,
    },
    {
      id: 'ds-bayonet-doppler',
      weapon: '★ Bayonet',
      skin: 'Doppler',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 1031.28,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEJheW9uZXQgfCBEb3BwbGVyIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.600,
    },
    {
      id: 'ds-flip-marble',
      weapon: '★ Flip Knife',
      skin: 'Marble Fade',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 660.99,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEZsaXAgS25pZmUgfCBNYXJibGUgRmFkZSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.800,
    },
    {
      id: 'ds-awp-lightning',
      weapon: 'AWP',
      skin: 'Lightning Strike',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 842.09,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgTGlnaHRuaW5nIFN0cmlrZSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.800,
    },
    {
      id: 'ds-ak-fireserpent-mw',
      weapon: 'AK-47',
      skin: 'Fire Serpent',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: false,
      price: 2281.42,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBGaXJlIFNlcnBlbnQgKE1pbmltYWwgV2Vhcik=.png',
      odds: 0.250,
      groupId: 'ds-ak-fireserpent',
    },
    {
      id: 'ds-ak-fireserpent-ft',
      weapon: 'AK-47',
      skin: 'Fire Serpent',
      rarity: 'Covert',
      condition: 'FT',
      statTrak: false,
      price: 808.33,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBGaXJlIFNlcnBlbnQgKE1pbmltYWwgV2Vhcik=.png',
      odds: 0.660,
      groupId: 'ds-ak-fireserpent',
    },
    {
      id: 'ds-m4a1s-printstream',
      weapon: 'M4A1-S',
      skin: 'Printstream',
      rarity: 'Covert',
      condition: 'BS',
      statTrak: false,
      price: 308.30,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgUHJpbnRzdHJlYW0gKEJhdHRsZS1TY2FycmVkKQ==.png',
      odds: 1.500,
    },
    {
      id: 'ds-daggers-slaughter',
      weapon: '★ Shadow Daggers',
      skin: 'Slaughter',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 272.08,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNoYWRvdyBEYWdnZXJzIHwgU2xhdWdodGVyIChGYWN0b3J5IE5ldyk=.png',
      odds: 2.500,
    },
    {
      id: 'ds-awp-oni-fn',
      weapon: 'AWP',
      skin: 'Oni Taiji',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 739.57,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgT25pIFRhaWppIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.900,
      groupId: 'ds-awp-oni',
    },
    {
      id: 'ds-awp-oni-ft',
      weapon: 'AWP',
      skin: 'Oni Taiji',
      rarity: 'Covert',
      condition: 'FT',
      statTrak: false,
      price: 245.57,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgT25pIFRhaWppIChGYWN0b3J5IE5ldyk=.png',
      odds: 2.000,
      groupId: 'ds-awp-oni',
    },
    {
      id: 'ds-gut-crimson',
      weapon: '★ Gut Knife',
      skin: 'Crimson Web',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 204.23,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEd1dCBLbmlmZSB8IENyaW1zb24gV2ViIChGaWVsZC1UZXN0ZWQp.png',
      odds: 3.500,
    },
    {
      id: 'ds-awp-asiimov',
      weapon: 'AWP',
      skin: 'Asiimov',
      rarity: 'Covert',
      condition: 'WW',
      statTrak: false,
      price: 126.37,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgQXNpaW1vdiAoV2VsbC1Xb3JuKQ==.png',
      odds: 4.600,
    },
    {
      id: 'ds-m4a4-asiimov',
      weapon: 'M4A4',
      skin: 'Asiimov',
      rarity: 'Covert',
      condition: 'BS',
      statTrak: false,
      price: 112.72,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IEFzaWltb3YgKEJhdHRsZS1TY2FycmVkKQ==.png',
      odds: 6.000,
    },
    {
      id: 'ds-m4a1s-playertwo',
      weapon: 'M4A1-S',
      skin: 'Player Two',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: false,
      price: 73.67,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgUGxheWVyIFR3byAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 7.000,
    },
    {
      id: 'ds-deagle-printstream',
      weapon: 'Desert Eagle',
      skin: 'Printstream',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: false,
      price: 61.72,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RGVzZXJ0IEVhZ2xlIHwgUHJpbnRzdHJlYW0gKE1pbmltYWwgV2Vhcik=.png',
      odds: 8.000,
    },
    {
      id: 'ds-ak-headshot',
      weapon: 'AK-47',
      skin: 'Head Shot',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 8.59,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBIZWFkIFNob3QgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 14.000,
    },
    {
      id: 'ds-awp-chromatic-fn',
      weapon: 'AWP',
      skin: 'Chromatic Aberration',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 37.87,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgQ2hyb21hdGljIEFiZXJyYXRpb24gKEZhY3RvcnkgTmV3KQ==.png',
      odds: 11.000,
      groupId: 'ds-awp-chromatic'
    },
    {
      id: 'ds-awp-chromatic-mw',
      weapon: 'AWP',
      skin: 'Chromatic Aberration',
      rarity: 'Restricted',
      condition: 'MW',
      statTrak: false,
      price: 57.24,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgQ2hyb21hdGljIEFiZXJyYXRpb24gKEZhY3RvcnkgTmV3KQ==.png',
      odds: 10.000,
      groupId: 'ds-awp-chromatic'
    },
    {
      id: 'ds-ak-icecoaled-fn',
      weapon: 'AK-47',
      skin: 'Ice Coaled',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 20.23,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBJY2UgQ29hbGVkIChGYWN0b3J5IE5ldyk=.png',
      odds: 13.300,
      groupId: 'ds-ak-icecoaled'
    },
    {
      id: 'ds-ak-icecoaled-mw',
      weapon: 'AK-47',
      skin: 'Ice Coaled',
      rarity: 'Restricted',
      condition: 'MW',
      statTrak: false,
      price: 50.56,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBJY2UgQ29hbGVkIChGYWN0b3J5IE5ldyk=.png',
      odds: 10.000,
      groupId: 'ds-ak-icecoaled'
    },
  ],
};