import { CSGOCase } from '../../../../types';

export const glovesCombatCase: CSGOCase = {
  id: 'gloves-combat',
  name: 'Gloves Combat',
  price: 75.38,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250731/809527329763119104.png',
  category: 'Creators',
  items: [
    {
      id: 'gc-moto-spearmint',
      weapon: '★ Moto Gloves',
      skin: 'Spearmint',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 5709.42,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE1vdG8gR2xvdmVzIHwgU3BlYXJtaW50IChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.050,
    },
    {
      id: 'gc-specialist-kimono',
      weapon: '★ Specialist Gloves',
      skin: 'Crimson Kimono',
      rarity: 'Extraordinary',
      condition: 'BS',
      statTrak: false,
      price: 2901.78,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwZWNpYWxpc3QgR2xvdmVzIHwgQ3JpbXNvbiBLaW1vbm8gKEJhdHRsZS1TY2FycmVkKQ==.png',
      odds: 0.080,
    },
    {
      id: 'gc-sport-slingshot',
      weapon: '★ Sport Gloves',
      skin: 'Slingshot',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 1368.73,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IFNsaW5nc2hvdCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.110,
    },
    {
      id: 'gc-specialist-tiger',
      weapon: '★ Specialist Gloves',
      skin: 'Tiger Strike',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 1436.57,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwZWNpYWxpc3QgR2xvdmVzIHwgVGlnZXIgU3RyaWtlIChNaW5pbWFsIFdlYXIp.png',
      odds: 0.120,
    },
    {
      id: 'gc-sport-nocts',
      weapon: '★ Sport Gloves',
      skin: 'Nocts',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 1375.18,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IE5vY3RzIChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.130,
    },
    {
      id: 'gc-driver-leopard',
      weapon: '★ Driver Gloves',
      skin: 'Snow Leopard',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 771.50,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIERyaXZlciBHbG92ZXMgfCBTbm93IExlb3BhcmQgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 0.200,
    },
    {
      id: 'gc-sport-omega',
      weapon: '★ Sport Gloves',
      skin: 'Omega',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 656.80,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IE9tZWdhIChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.300,
    },
    {
      id: 'gc-sport-scarlet',
      weapon: '★ Sport Gloves',
      skin: 'Scarlet Shamagh',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 615.36,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IFNjYXJsZXQgU2hhbWFnaCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.360,
    },
    {
      id: 'gc-driver-plaid',
      weapon: '★ Driver Gloves',
      skin: 'Imperial Plaid',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 561.33,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIERyaXZlciBHbG92ZXMgfCBJbXBlcmlhbCBQbGFpZCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.380,
    },
    {
      id: 'gc-moto-turtle',
      weapon: '★ Moto Gloves',
      skin: 'Turtle',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 518.15,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE1vdG8gR2xvdmVzIHwgVHVydGxlIChNaW5pbWFsIFdlYXIp.png',
      odds: 0.600,
    },
    {
      id: 'gc-moto-blood',
      weapon: '★ Moto Gloves',
      skin: 'Blood Pressure',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 325.08,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE1vdG8gR2xvdmVzIHwgQmxvb2QgUHJlc3N1cmUgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 0.770,
    },
    {
      id: 'gc-moto-pow',
      weapon: '★ Moto Gloves',
      skin: 'POW!',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 316.99,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE1vdG8gR2xvdmVzIHwgUE9XISAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.800,
    },
    {
      id: 'gc-brokenfang-jade',
      weapon: '★ Broken Fang Gloves',
      skin: 'Jade',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 239.23,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEJyb2tlbiBGYW5nIEdsb3ZlcyB8IEphZGUgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 1.100,
    },
    {
      id: 'gc-driver-rezan',
      weapon: '★ Driver Gloves',
      skin: 'Rezan the Red',
      rarity: 'Extraordinary',
      condition: 'BS',
      statTrak: false,
      price: 189.29,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIERyaXZlciBHbG92ZXMgfCBSZXphbiB0aGUgUmVkIChCYXR0bGUtU2NhcnJlZCk=.png',
      odds: 1.600,
    },
    {
      id: 'gc-driver-overtake',
      weapon: '★ Driver Gloves',
      skin: 'Overtake',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 148.37,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIERyaXZlciBHbG92ZXMgfCBPdmVydGFrZSAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 2.500,
    },
    {
      id: 'gc-st-ssg-dragonfire',
      weapon: 'StatTrak™ SSG 08',
      skin: 'Dragonfire',
      rarity: 'Covert',
      condition: 'FT',
      statTrak: true,
      price: 79.29,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U3RhdFRyYWvihKIgU1NHIDA4IHwgRHJhZ29uZmlyZSAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 9.900,
    },
    {
      id: 'gc-m4a4-hellfire',
      weapon: 'M4A4',
      skin: 'Hellfire',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 67.33,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IEhlbGxmaXJlIChGaWVsZC1UZXN0ZWQp.png',
      odds: 13.000,
    },
    {
      id: 'gc-m4a1s-playertwo',
      weapon: 'M4A1-S',
      skin: 'Player Two',
      rarity: 'Covert',
      condition: 'FT',
      statTrak: false,
      price: 30.56,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgUGxheWVyIFR3byAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 14.000,
    },
    {
      id: 'gc-st-ak-anubis',
      weapon: 'StatTrak™ AK-47',
      skin: 'Legion of Anubis',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: true,
      price: 24.97,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U3RhdFRyYWvihKIgQUstNDcgfCBMZWdpb24gb2YgQW51YmlzIChGaWVsZC1UZXN0ZWQp.png',
      odds: 16.000,
    },
    {
      id: 'gc-deagle-mecha',
      weapon: 'Desert Eagle',
      skin: 'Mecha Industries',
      rarity: 'Mil-Spec',
      condition: 'FN',
      statTrak: false,
      price: 31.53,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RGVzZXJ0IEVhZ2xlIHwgTWVjaGEgSW5kdXN0cmllcyAoRmFjdG9yeSBOZXcp.png',
      odds: 18.000,
    },
    {
      id: 'gc-ak-headshot',
      weapon: 'AK-47',
      skin: 'Head Shot',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 8.59,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBIZWFkIFNob3QgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 20.000,
    },
  ],
};