import { CSGOCase } from '../../../../types';

export const gloverCase: CSGOCase = {
  id: 'glover',
  name: 'Glover',
  price: 79.69,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250731/809530820275490816.png',
  category: 'Creators',
  items: [
    {
      id: 'gl-gloves-kimono',
      weapon: '★ Specialist Gloves',
      skin: 'Crimson Kimono',
      rarity: 'Extraordinary',
      condition: 'BS',
      statTrak: false,
      price: 2901.78,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwZWNpYWxpc3QgR2xvdmVzIHwgQ3JpbXNvbiBLaW1vbm8gKEJhdHRsZS1TY2FycmVkKQ==.png',
      odds: 0.100,
    },
    {
      id: 'gl-gloves-amphibious',
      weapon: '★ Sport Gloves',
      skin: 'Amphibious',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 2615.29,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IEFtcGhpYmlvdXMgKE1pbmltYWwgV2Vhcik=.png',
      odds: 0.200,
    },
    {
      id: 'gl-gloves-omega',
      weapon: '★ Sport Gloves',
      skin: 'Omega',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 1705.77,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IE9tZWdhIChNaW5pbWFsIFdlYXIp.png',
      odds: 0.400,
    },
    {
      id: 'gl-wraps-cobalt-mw',
      weapon: '★ Hand Wraps',
      skin: 'Cobalt Skulls',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 1298.95,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEhhbmQgV3JhcHMgfCBDb2JhbHQgU2t1bGxzIChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.700,
      groupId: 'gl-wraps-cobalt',
    },
    {
      id: 'gl-wraps-cobalt-ft',
      weapon: '★ Hand Wraps',
      skin: 'Cobalt Skulls',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 658.94,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEhhbmQgV3JhcHMgfCBDb2JhbHQgU2t1bGxzIChGaWVsZC1UZXN0ZWQp.png',
      odds: 2.700,
      groupId: 'gl-wraps-cobalt',
    },
    {
      id: 'gl-gloves-bronze',
      weapon: '★ Sport Gloves',
      skin: 'Bronze Morph',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 487.05,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IEJyb256ZSBNb3JwaCAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 6.000,
    },
    {
      id: 'gl-duals-balance',
      weapon: 'Dual Berettas',
      skin: 'Balance',
      rarity: 'Restricted',
      condition: 'FT',
      statTrak: false,
      price: 1.64,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RHVhbCBCZXJldHRhcyB8IEJhbGFuY2UgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 15.000,
    },
    {
      id: 'gl-cz75-eco',
      weapon: 'CZ75-Auto',
      skin: 'Eco',
      rarity: 'Restricted',
      condition: 'WW',
      statTrak: false,
      price: 0.95,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/Q1o3NS1BdXRvIHwgRWNvIChXZWxsLVdvcm4p.png',
      odds: 18.000,
    },
    {
      id: 'gl-p2000-acid',
      weapon: 'P2000',
      skin: 'Acid Etched',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 0.61,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/UDIwMDAgfCBBY2lkIEV0Y2hlZCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 18.000,
    },
    {
      id: 'gl-ak47-uncharted',
      weapon: 'AK-47',
      skin: 'Uncharted',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 0.40,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBVbmNoYXJ0ZWQgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 19.000,
    },
    {
      id: 'gl-glock-highbeam',
      weapon: 'Glock-18',
      skin: 'High Beam',
      rarity: 'Industrial',
      condition: 'FN',
      statTrak: false,
      price: 0.30,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/R2xvY2stMTggfCBIaWdoIEJlYW0gKEZhY3RvcnkgTmV3KQ==.png',
      odds: 19.900,
    },
  ],
};
