import { CSGOCase } from '../../../../types';

export const hanamiCase: CSGOCase = {
  id: 'hanami',
  name: 'Hanami',
  price: 100000.00,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250731/809530669024694272.png',
  category: 'Creators',
  items: [
    {
      id: 'ha-stiletto-slaughter',
      weapon: '★ Stiletto Knife',
      skin: 'Slaughter',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 938.89,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFN0aWxldHRvIEtuaWZlIHwgU2xhdWdodGVyIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.100,
    },
    {
      id: 'ha-flip-slaughter',
      weapon: '★ Flip Knife',
      skin: 'Slaughter',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 605.74,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEZsaXAgS25pZmUgfCBTbGF1Z2h0ZXIgKE1pbmltYWwgV2Vhcik=.png',
      odds: 0.200,
    },
    {
      id: 'ha-m4a1s-printstream',
      weapon: 'M4A1-S',
      skin: 'Printstream',
      rarity: 'Covert',
      condition: 'WW',
      statTrak: false,
      price: 450.00, // Corrected from an extremely high outlier value
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgUHJpbnRzdHJlYW0gKFdlbGwtV29ybik=.png',
      odds: 0.300,
    },
    {
      id: 'ha-survival-slaughter',
      weapon: '★ Survival Knife',
      skin: 'Slaughter',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 313.11,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFN1cnZpdmFsIEtuaWZlIHwgU2xhdWdodGVyIChNaW5pbWFsIFdlYXIp.png',
      odds: 0.400,
    },
    {
      id: 'ha-ak47-bloodsport',
      weapon: 'AK-47',
      skin: 'Bloodsport',
      rarity: 'Covert',
      condition: 'FT',
      statTrak: false,
      price: 237.90,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBCbG9vZHNwb3J0IChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.500,
    },
    {
      id: 'ha-fiveseven-berries',
      weapon: 'Five-SeveN',
      skin: 'Berries And Cherries',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 167.80,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/Rml2ZS1TZXZlTiB8IEJlcnJpZXMgQW5kIENoZXJyaWVzIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.600,
    },
    {
      id: 'ha-mac10-ch',
      weapon: 'MAC-10',
      skin: 'Case Hardened',
      rarity: 'Restricted',
      condition: 'MW',
      statTrak: false,
      price: 171.70,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TUFDLTEwIHwgQ2FzZSBIYXJkZW5lZCAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 0.800,
    },
    {
      id: 'ha-galil-eco',
      weapon: 'Galil AR',
      skin: 'Eco',
      rarity: 'Restricted',
      condition: 'MW',
      statTrak: false,
      price: 91.69,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/R2FsaWwgQVIgfCBFY28gKE1pbmltYWwgV2Vhcik=.png',
      odds: 2.000,
    },
    {
      id: 'ha-awp-redline',
      weapon: 'AWP',
      skin: 'Redline',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 60.37,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgUmVkbGluZSAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 2.500,
    },
    {
      id: 'ha-m4a1s-playertwo-mw',
      weapon: 'M4A1-S',
      skin: 'Player Two',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: false,
      price: 73.67,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgUGxheWVyIFR3byAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 2.000,
      groupId: 'ha-m4a1s-playertwo',
    },
    {
      id: 'ha-m4a1s-playertwo-ft',
      weapon: 'M4A1-S',
      skin: 'Player Two',
      rarity: 'Covert',
      condition: 'FT',
      statTrak: false,
      price: 139.17,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgUGxheWVyIFR3byAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 1.000,
      groupId: 'ha-m4a1s-playertwo',
    },
    {
      id: 'ha-fiveseven-fairytale',
      weapon: 'Five-SeveN',
      skin: 'Fairy Tale',
      rarity: 'Restricted',
      condition: 'WW',
      statTrak: false,
      price: 36.63,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/Rml2ZS1TZXZlTiB8IEZhaXJ5IFRhbGUgKFdlbGwtV29ybik=.png',
      odds: 4.000,
    },
    {
      id: 'ha-mac10-stalker',
      weapon: 'MAC-10',
      skin: 'Stalker',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: false,
      price: 39.51,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TUFDLTEwIHwgU3RhbGtlciAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 5.000,
    },
    {
      id: 'ha-usps-printstream',
      weapon: 'USP-S',
      skin: 'Printstream',
      rarity: 'Covert',
      condition: 'BS',
      statTrak: false,
      price: 35.14,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/VVNQLVMgfCBQcmludHN0cmVhbSAoQmF0dGxlLVNjYXJyZWQp.png',
      odds: 6.600,
    },
    {
      id: 'ha-st-galil-rocketpop',
      weapon: 'StatTrak™ Galil AR',
      skin: 'Rocket Pop',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: true,
      price: 31.29,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U3RhdFRyYWvihKIgR2FsaWwgQVIgfCBSb2NrZXQgUG9wIChGYWN0b3J5IE5ldyk=.png',
      odds: 8.000,
    },
    {
      id: 'ha-galil-chatterbox',
      weapon: 'Galil AR',
      skin: 'Chatterbox',
      rarity: 'Covert',
      condition: 'WW',
      statTrak: false,
      price: 27.61,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/R2FsaWwgQVIgfCBDaGF0dGVyYm94IChXZWxsLVdvcm4p.png',
      odds: 9.000,
    },
    {
      id: 'ha-ak47-pointdisarray',
      weapon: 'AK-47',
      skin: 'Point Disarray',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 15.86,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBQb2ludCBEaXNhcnJheSAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 12.000,
    },
    {
      id: 'ha-m4a4-dragonking',
      weapon: 'M4A4',
      skin: '龍王 (Dragon King)',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 14.04,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IOm=jeeOiyAoRHJhZ29uIEtpbmcpIChGaWVsZC1UZXN0ZWQp.png',
      odds: 13.000,
    },
    {
      id: 'ha-glock-wastelandrebel',
      weapon: 'Glock-18',
      skin: 'Wasteland Rebel',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 42.37,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/R2xvY2stMTggfCBXYXN0ZWxhbmQgUmViZWwgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 15.000,
    },
    {
      id: 'ha-deagle-conspiracy',
      weapon: 'Desert Eagle',
      skin: 'Conspiracy',
      rarity: 'Restricted',
      condition: 'MW',
      statTrak: false,
      price: 10.58,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RGVzZXJ0IEVhZ2xlIHwgQ29uc3BpcmFjeSAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 17.000,
    },
  ],
};