import { CSGOCase } from '../../../../types';

export const hotCase: CSGOCase = {
  id: 'hot',
  name: 'Hot',
  price: 10.37,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250731/809530054882119680.png',
  category: 'Creators',
  items: [
    {
      id: 'hot-huntsman-tiger',
      weapon: '★ Huntsman Knife',
      skin: 'Tiger Tooth',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 414.22,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEh1bnRzbWFuIEtuaWZlIHwgVGlnZXIgVG9vdGggKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.050,
    },
    {
      id: 'hot-awp-oni',
      weapon: 'AWP',
      skin: 'Oni Taiji',
      rarity: 'Covert',
      condition: 'FT',
      statTrak: false,
      price: 334.59,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgT25pIFRhaWppIChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.150,
    },
    {
      id: 'hot-awp-wildfire',
      weapon: 'AWP',
      skin: 'Wildfire',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 67.54,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgV2lsZGZpcmUgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 1.700,
    },
    {
      id: 'hot-m4a1s-atomic',
      weapon: 'M4A1-S',
      skin: 'Atomic Alloy',
      rarity: 'Classified',
      condition: 'MW',
      statTrak: false,
      price: 85.96,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgQXRvbWljIEFsbG95IChNaW5pbWFsIFdlYXIp.png',
      odds: 2.000,
    },
    {
      id: 'hot-m4a4-spider',
      weapon: 'M4A4',
      skin: 'Spider Lily',
      rarity: 'Restricted',
      condition: 'FT',
      statTrak: false,
      price: 7.11,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IFNwaWRlciBMaWx5IChGaWVsZC1UZXN0ZWQp.png',
      odds: 8.000,
    },
    {
      id: 'hot-famas-roll',
      weapon: 'FAMAS',
      skin: 'Roll Cage',
      rarity: 'Restricted',
      condition: 'MW',
      statTrak: false,
      price: 7.94,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RkFNQVMgfCBSb2xsIENhZ2UgKE1pbmltYWwgV2Vhcik=.png',
      odds: 12.600,
    },
    {
      id: 'hot-m4a4-daimyo',
      weapon: 'M4A4',
      skin: 'Evil Daimyo',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 21.70,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IEV2aWwgRGFpbXlvIChGYWN0b3J5IE5ldyk=.png',
      odds: 17.500,
    },
    {
      id: 'hot-cz-tigris',
      weapon: 'CZ75-Auto',
      skin: 'Tigris',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 1.11,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/Q1o3NS1BdXRvIHwgVGlncmlzIChGaWVsZC1UZXN0ZWQp.png',
      odds: 18.000,
    },
    {
      id: 'hot-galil-firefight',
      weapon: 'Galil AR',
      skin: 'Firefight',
      rarity: 'Mil-Spec',
      condition: 'WW',
      statTrak: false,
      price: 0.53,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/R2FsaWwgQVIgfCBGaXJlZmlnaHQgKFdlbGwtV29ybik=.png',
      odds: 20.000,
    },
    {
      id: 'hot-m4a1s-terror',
      weapon: 'M4A1-S',
      skin: 'Night Terror',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 0.46,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgTmlnaHQgVGVycm9yIChGaWVsZC1UZXN0ZWQp.png',
      odds: 20.000,
    },
  ],
};