import { CSGOCase } from '../../../../types';

export const mazeTripCase: CSGOCase = {
  id: 'maze-trip',
  name: 'Maze Trip',
  price: 1260.44,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250731/809531144235143168.png',
  category: 'Creators',
  items: [
    {
      id: 'mt-gloves-hedgemaze',
      weapon: '★ Sport Gloves',
      skin: 'Hedge Maze',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 12603.29,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IEhlZGdlIE1hemUgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 0.300,
    },
    {
      id: 'mt-m4a4-howl',
      weapon: 'M4A4',
      skin: 'Howl',
      rarity: 'Contraband',
      condition: 'FN',
      statTrak: false,
      price: 11368.71,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IEhvd2wgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.500,
    },
    {
      id: 'mt-awp-dragonlore',
      weapon: 'AWP',
      skin: 'Dragon Lore',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: false,
      price: 14733.78,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgRHJhZ29uIExvcmUgKE1pbmltYWwgV2Vhcik=.png',
      odds: 0.900,
    },
    {
      id: 'mt-awp-prince',
      weapon: 'AWP',
      skin: 'The Prince',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: false,
      price: 3836.98,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgVGhlIFByaW5jZSAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 1.000,
    },
    {
      id: 'mt-m4a1s-jungle',
      weapon: 'M4A1-S',
      skin: 'Welcome to the Jungle',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 3969.69,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgV2VsY29tZSB0byB0aGUgSnVuZ2xlIChGYWN0b3J5IE5ldyk=.png',
      odds: 1.100,
    },
    {
      id: 'mt-gloves-arid',
      weapon: '★ Sport Gloves',
      skin: 'Arid',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 4215.56,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IEFyaWQgKE1pbmltYWwgV2Vhcik=.png',
      odds: 1.200,
    },
    {
      id: 'mt-m9-lore',
      weapon: '★ M9 Bayonet',
      skin: 'Lore',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 3785.61,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE05IEJheW9uZXQgfCBMb3JlIChGYWN0b3J5IE5ldyk=.png',
      odds: 1.800,
    },
    {
      id: 'mt-karambit-lore',
      weapon: '★ Karambit',
      skin: 'Lore',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 3419.73,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEthcmFtYml0IHwgTG9yZSAoRmFjdG9yeSBOZXcp.png',
      odds: 2.000,
    },
    {
      id: 'mt-bfk-lore',
      weapon: '★ Butterfly Knife',
      skin: 'Lore',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 2987.52,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEJ1dHRlcmZseSBLbmlmZSB8IExvcmUgKE1pbmltYWwgV2Vhcik=.png',
      odds: 2.200,
    },
    {
      id: 'mt-ak47-xray',
      weapon: 'AK-47',
      skin: 'X-Ray',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: false,
      price: 2208.05,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBYLVJheSAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 3.000,
    },
    {
      id: 'mt-gloves-scarlet',
      weapon: '★ Sport Gloves',
      skin: 'Scarlet Shamagh',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 1191.71,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IFNjYXJsZXQgU2hhbWFnaCAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 7.000,
    },
    {
      id: 'mt-talon-tiger',
      weapon: '★ Talon Knife',
      skin: 'Tiger Tooth',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 1180.36,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFRhbG9uIEtuaWZlIHwgVGlnZXIgVG9vdGggKEZhY3RvcnkgTmV3KQ==.png',
      odds: 9.000,
    },
    {
      id: 'mt-gloves-omega',
      weapon: '★ Sport Gloves',
      skin: 'Omega',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 656.80,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IE9tZWdhIChGaWVsZC1UZXN0ZWQp.png',
      odds: 12.000,
    },
    {
      id: 'mt-bowie-marble',
      weapon: '★ Bowie Knife',
      skin: 'Marble Fade',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 449.14,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEJvd2llIEtuaWZlIHwgTWFyYmxlIEZhZGUgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 13.000,
    },
    {
      id: 'mt-specialist-fade',
      weapon: '★ Specialist Gloves',
      skin: 'Fade',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 568.91,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwZWNpYWxpc3QgR2xvdmVzIHwgRmFkZSAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 13.000,
    },
    {
      id: 'mt-bayonet-damascus',
      weapon: '★ Bayonet',
      skin: 'Damascus Steel',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 397.93,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEJheW9uZXQgfCBEYW1hc2N1cyBTdGVlbCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 16.000,
    },
    {
      id: 'mt-kukri-slaughter',
      weapon: '★ Kukri Knife',
      skin: 'Slaughter',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 406.82,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEt1a3JpIEtuaWZlIHwgU2xhdWdodGVyIChNaW5pbWFsIFdlYXIp.png',
      odds: 16.000,
    },
  ],
};