import { CSGOCase } from '../../../../types';

export const newToTownCase: CSGOCase = {
  id: 'new-to-town',
  name: 'New to Town',
  price: 0.53,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250731/809525231906476032.png',
  category: 'Creators',
  items: [
    {
      id: 'ntt-m4a1s-mecha',
      weapon: 'M4A1-S',
      skin: 'Mecha Industries',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: false,
      price: 85.75,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgTWVjaGEgSW5kdXN0cmllcyAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 0.030,
    },
    {
      id: 'ntt-awp-neonoit',
      weapon: 'AWP',
      skin: 'Neo-Noir',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 80.41,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgTmVvLU5vaXIgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.050,
    },
    {
      id: 'ntt-ak47-nightwish',
      weapon: 'AK-47',
      skin: 'Nightwish',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 9.76,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBOaWdodHdpc2ggKEZpZWxkLVRlc3RlZCk=.png',
      odds: 0.080,
    },
    {
      id: 'ntt-p250-seeya',
      weapon: 'P250',
      skin: 'See Ya Later',
      rarity: 'Classified',
      condition: 'MW',
      statTrak: false,
      price: 16.68,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/UDI1MCB8IFNlZSBZYSBMYXRlciAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 0.100,
    },
    {
      id: 'ntt-m4a4-daimyo',
      weapon: 'M4A4',
      skin: 'Evil Daimyo',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 21.70,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IEV2aWwgRGFpbXlvIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.110,
    },
    {
      id: 'ntt-deagle-mecha',
      weapon: 'Desert Eagle',
      skin: 'Mecha Industries',
      rarity: 'Restricted',
      condition: 'FT',
      statTrak: false,
      price: 6.45,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RGVzZXJ0IEVhZ2xlIHwgTWVjaGEgSW5kdXN0cmllcyAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.110,
    },
    {
      id: 'ntt-glock-vogue',
      weapon: 'Glock-18',
      skin: 'Vogue',
      rarity: 'Restricted',
      condition: 'FT',
      statTrak: false,
      price: 3.02,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/R2xvY2stMTggfCBWb2d1ZSAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.110,
    },
    {
      id: 'ntt-ak47-icecoaled',
      weapon: 'AK-47',
      skin: 'Ice Coaled',
      rarity: 'Restricted',
      condition: 'FT',
      statTrak: false,
      price: 4.84,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBJY2UgQ29hbGVkIChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.110,
    },
    {
      id: 'ntt-galil-kami',
      weapon: 'Galil AR',
      skin: 'Kami',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 2.86,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/R2FsaWwgQVIgfCBLYW1pIChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.500,
    },
    {
      id: 'ntt-aug-momentum',
      weapon: 'AUG',
      skin: 'Momentum',
      rarity: 'Restricted',
      condition: 'FT',
      statTrak: false,
      price: 2.33,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVVHIHwgTW9tZW50dW0gKEZpZWxkLVRlc3RlZCk=.png',
      odds: 0.700,
    },
    {
      id: 'ntt-tec9-reentry',
      weapon: 'Tec-9',
      skin: 'Re-Entry',
      rarity: 'Mil-Spec',
      condition: 'MW',
      statTrak: false,
      price: 1.14,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/VGVjLTkgfCBSZS1FbnRyeSAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 1.500,
    },
    {
      id: 'ntt-sawedoff-apocalypto',
      weapon: 'Sawed-Off',
      skin: 'Apocalypto',
      rarity: 'Restricted',
      condition: 'MW',
      statTrak: false,
      price: 2.03,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U2F3ZWQtT2ZmIHwgQXBvY2FseXB0byAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 2.000,
    },
    {
      id: 'ntt-glock-rabbit',
      weapon: 'Glock-18',
      skin: 'Umbral Rabbit',
      rarity: 'Mil-Spec',
      condition: 'MW',
      statTrak: false,
      price: 0.77,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/R2xvY2stMTggfCBVbWJyYWwgUmFiYml0IChNaW5pbWFsIFdlYXIp.png',
      odds: 2.000,
    },
    {
      id: 'ntt-r8-banana',
      weapon: 'R8 Revolver',
      skin: 'Banana Cannon',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 0.21,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/UjggUmV2b2x2ZXIgfCBCYW5hbmEgQ2Fubm9uIChGaWVsZC1UZXN0ZWQp.png',
      odds: 4.000,
    },
    {
      id: 'ntt-fiveseven-daimyo',
      weapon: 'Five-SeveN',
      skin: 'Violent Daimyo',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 0.40,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/Rml2ZS1TZXZlTiB8IFZpb2xlbnQgRGFpbXlvIChGaWVsZC1UZXN0ZWQp.png',
      odds: 7.600,
    },
    {
      id: 'ntt-duals-dragons',
      weapon: 'Dual Berettas',
      skin: 'Dualing Dragons',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 0.44,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RHVhbCBCZXJldHRhcyB8IER1YWxpbmcgRHJhZ29ucyAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 8.000,
    },
    {
      id: 'ntt-m4a4-magnesium',
      weapon: 'M4A4',
      skin: 'Magnesium',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 0.48,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IE1hZ25lc2l1bSAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 10.000,
    },
    {
      id: 'ntt-mp7-cirrus',
      weapon: 'MP7',
      skin: 'Cirrus',
      rarity: 'Industrial',
      condition: 'FT',
      statTrak: false,
      price: 0.38,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TVA3IHwgQ2lycnVzIChGaWVsZC1UZXN0ZWQp.png',
      odds: 11.000,
    },
    {
      id: 'ntt-deagle-blueply',
      weapon: 'Desert Eagle',
      skin: 'Blue Ply',
      rarity: 'Industrial',
      condition: 'FT',
      statTrak: false,
      price: 0.33,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RGVzZXJ0IEVhZ2xlIHwgQmx1ZSBQbHkgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 11.000,
    },
    {
      id: 'ntt-cz75-circaetus',
      weapon: 'CZ75-Auto',
      skin: 'Circaetus',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 0.26,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/Q1o3NS1BdXRvIHwgQ2lyY2FldHVzIChGaWVsZC1UZXN0ZWQp.png',
      odds: 12.000,
    },
    {
      id: 'ntt-sg553-cyberforce',
      weapon: 'SG 553',
      skin: 'Cyberforce',
      rarity: 'Industrial',
      condition: 'MW',
      statTrak: false,
      price: 0.08,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U0cgNTUzIHwgQ3liZXJmb3JjZSAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 14.000,
    },
    {
      id: 'ntt-p250-cassette',
      weapon: 'P250',
      skin: 'Cassette',
      rarity: 'Industrial',
      condition: 'FT',
      statTrak: false,
      price: 0.04,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/UDI1MCB8IENhc3NldHRlIChGaWVsZC1UZXN0ZWQp.png',
      odds: 15.000,
    },
  ],
};