
import { CSGOCase } from '../../../../types';

export const redAlertCase: CSGOCase = {
  id: 'red-alert',
  name: 'Red Alert',
  price: 6.09,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250811/813426819066781696.png',
  category: 'Official',
  items: [
    {
      id: 'ra-01',
      weapon: '★ Gut Knife',
      skin: 'Slaughter',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 313.21,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEd1dCBLbmlmZSB8IFNsYXVnaHRlciAoRmFjdG9yeSBOZXcp.png',
      odds: 0.050,
    },
    {
      id: 'ra-02',
      weapon: '★ Gut Knife',
      skin: 'Autotronic',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 285.25,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEd1dCBLbmlmZSB8IEF1dG90cm9uaWMgKE1pbmltYWwgV2Vhcik=.png',
      odds: 0.050,
    },
    {
      id: 'ra-03',
      weapon: '★ Shadow Daggers',
      skin: 'Slaughter',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 272.18,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNoYWRvdyBEYWdnZXJzIHwgU2xhdWdodGVyIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.060,
    },
    {
      id: 'ra-04',
      weapon: '★ Gut Knife',
      skin: 'Crimson Web',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 265.63,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEZhbGNoaW9uIEtuaWZlIHwgQ3JpbXNvbiBXZWIgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 0.060,
    },
    {
      id: 'ra-05',
      weapon: '★ Falchion Knife',
      skin: 'Crimson Web',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 255.61,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEZhbGNoaW9uIEtuaWZlIHwgQ3JpbXNvbiBXZWIgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 0.060,
    },
    {
      id: 'ra-06',
      weapon: 'P90',
      skin: 'Cold Blooded',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: true,
      price: 120.08,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U3RhdFRyYWvihKIgUDkwIHwgQ29sZCBCbG9vZGVkIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.130,
    },
    {
      id: 'ra-07',
      weapon: '★ Shadow Daggers',
      skin: 'Crimson Web',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 218.36,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNoYWRvdyBEYWdnZXJzIHwgQ3JpbXNvbiBXZWIgKE1pbmltYWwgV2Vhcik=.png',
      odds: 0.170,
    },
    {
      id: 'ra-08',
      weapon: 'Desert Eagle',
      skin: 'Crimson Web',
      rarity: 'Classified',
      condition: 'MW',
      statTrak: false,
      price: 44.79,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RGVzZXJ0IEVhZ2xlIHwgQ3JpbXNvbiBXZWIgKE1pbmltYWwgV2Vhcik=.png',
      odds: 0.620,
    },
    {
      id: 'ra-09',
      weapon: 'P250',
      skin: 'Muertos',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 42.77,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/UDI1MCB8IE11ZXJ0b3MgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 1.700,
    },
    {
      id: 'ra-10',
      weapon: 'M4A1-S',
      skin: 'Blood Tiger',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 11.86,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgQmxvb2QgVGlnZXIgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 3.600,
    },
    {
      id: 'ra-11',
      weapon: 'USP-S',
      skin: 'Blood Tiger',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 3.90,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/VVNQLVMgfCBCbG9vZCBUaWdlciAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 5.500,
    },
    {
      id: 'ra-12',
      weapon: 'SCAR-20',
      skin: 'Bloodsport',
      rarity: 'Restricted',
      condition: 'FT',
      statTrak: false,
      price: 3.91,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U0NBUi0yMCB8IEJsb29kc3BvcnQgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 8.000,
    },
    {
      id: 'ra-13',
      weapon: 'Galil AR',
      skin: 'Crimson Tsunami',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 2.24,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/R2FsaWwgQVIgfCBDcmltc29uIFRzdW5hbWkgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 10.000,
    },
    {
      id: 'ra-14',
      weapon: 'M4A4',
      skin: 'Spider Lily',
      rarity: 'Restricted',
      condition: 'BS',
      statTrak: false,
      price: 4.37,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IFNwaWRlciBMaWx5IChCYXR0bGUtU2NhcnJlZCk=.png',
      odds: 12.000,
    },
    {
      id: 'ra-15',
      weapon: 'SCAR-20',
      skin: 'Crimson Web',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 3.67,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U0NBUi0yMCB8IENyaW1zb24gV2ViIChGaWVsZC1UZXN0ZWQp.png',
      odds: 13.000,
    },
    {
      id: 'ra-16',
      weapon: 'R8 Revolver',
      skin: 'Crimson Web',
      rarity: 'Mil-Spec',
      condition: 'MW',
      statTrak: true,
      price: 2.65,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U3RhdFRyYWvihKIgUjggUmV2b2x2ZXIgfCBDcmltc29uIFdlYiAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 14.000,
    },
    {
      id: 'ra-17',
      weapon: 'MP7',
      skin: 'Bloodsport',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 2.29,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TVA3IHwgQmxvb2RzcG9ydCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 15.000,
    },
    {
      id: 'ra-18',
      weapon: 'CZ75-Auto',
      skin: 'Crimson Web',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 1.22,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/Q1o3NS1BdXRvIHwgQ3JpbXNvbiBXZWIgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 16.000,
    },
  ],
};
