import { CSGOCase } from '../../../../types';

export const starPearlCase: CSGOCase = {
  id: 'star-pearl',
  name: 'Star Pearl',
  price: 100000.00,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250731/809530910264283136.png',
  category: 'Creators',
  items: [
    {
      id: 'sp-awp-fade',
      weapon: 'AWP',
      skin: 'Fade',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 1387.45,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgRmFkZSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.500,
    },
    {
      id: 'sp-ursus-doppler',
      weapon: '★ Ursus Knife',
      skin: 'Doppler',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 655.34,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFVyc3VzIEtuaWZlIHwgRG9wcGxlciAoRmFjdG9yeSBOZXcp.png',
      odds: 1.000,
    },
    {
      id: 'sp-ak47-xray',
      weapon: 'AK-47',
      skin: 'X-Ray',
      rarity: 'Covert',
      condition: 'WW',
      statTrak: false,
      price: 634.08,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBYLVJheSAoV2VsbC1Xb3JuKQ==.png',
      odds: 1.000,
    },
    {
      id: 'sp-navaja-marble',
      weapon: '★ Navaja Knife',
      skin: 'Marble Fade',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 227.96,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE5hdmFqYSBLbmlmZSB8IE1hcmJsZSBGYWRlIChGYWN0b3J5IE5ldyk=.png',
      odds: 3.000,
    },
    {
      id: 'sp-m4a1s-printstream',
      weapon: 'M4A1-S',
      skin: 'Printstream',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: false,
      price: 551.28,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgUHJpbnRzdHJlYW0gKE1pbmltYWwgV2Vhcik=.png',
      odds: 3.000,
    },
    {
      id: 'sp-daggers-ch',
      weapon: '★ Shadow Daggers',
      skin: 'Case Hardened',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 201.98,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNoYWRvdyBEYWdnZXJzIHwgQ2FzZSBIYXJkZW5lZCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 4.000,
    },
    {
      id: 'sp-m4a4-noir-st',
      weapon: 'M4A4',
      skin: 'Neo-Noir',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: true,
      price: 70.60,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U3RhdFRyYWvihKIgTTRBNCB8IE5lby1Ob2lyIChNaW5pbWFsIFdlYXIp.png',
      odds: 9.000,
    },
    {
      id: 'sp-m4a1s-mecha',
      weapon: 'M4A1-S',
      skin: 'Mecha Industries',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 40.51,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgTWVjaGEgSW5kdXN0cmllcyAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 13.500,
    },
    {
      id: 'sp-deagle-kumicho',
      weapon: 'Desert Eagle',
      skin: 'Kumicho Dragon',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 28.26,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RGVzZXJ0IEVhZ2xlIHwgS3VtaWNobyBEcmFnb24gKEZpZWxkLVRlc3RlZCk=.png',
      odds: 16.000,
    },
    {
      id: 'sp-usps-cortex',
      weapon: 'USP-S',
      skin: 'Cortex',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 28.46,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/VVNQLVMgfCBDb3J0ZXggKEZhY3RvcnkgTmV3KQ==.png',
      odds: 24.000,
    },
    {
      id: 'sp-deagle-mecha',
      weapon: 'Desert Eagle',
      skin: 'Mecha Industries',
      rarity: 'Mil-Spec',
      condition: 'FN',
      statTrak: false,
      price: 31.53,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RGVzZXJ0IEVhZ2xlIHwgTWVjaGEgSW5kdXN0cmllcyAoRmFjdG9yeSBOZXcp.png',
      odds: 25.000,
    },
  ],
};