import { CSGOCase } from '../../../../types';

export const tenPercentKnifeCase: CSGOCase = {
  id: 'ten-percent-knife',
  name: '10% Knife',
  price: 25.69,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250815/814831560585953280.png',
  category: 'Official',
  items: [
    {
      id: 'tk-bfk-fade',
      weapon: '★ Butterfly Knife',
      skin: 'Fade',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 6487.05,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEJ1dHRlcmZseSBLbmlmZSB8IEZhZGUgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.002,
    },
    {
      id: 'tk-kar-gamma',
      weapon: '★ Karambit',
      skin: 'Gamma Doppler',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 6804.24,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEthcmFtYml0IHwgR2FtbWEgRG9wcGxlciAoRmFjdG9yeSBOZXcp.png',
      odds: 0.002,
    },
    {
      id: 'tk-m9-lore',
      weapon: '★ M9 Bayonet',
      skin: 'Lore',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 3785.61,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE05IEJheW9uZXQgfCBMb3JlIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.010,
    },
    {
      id: 'tk-kar-doppler',
      weapon: '★ Karambit',
      skin: 'Doppler',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 3969.78,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEthcmFtYml0IHwgRG9wcGxlciAoRmFjdG9yeSBOZXcp.png',
      odds: 0.020,
    },
    {
      id: 'tk-kar-marble',
      weapon: '★ Karambit',
      skin: 'Marble Fade',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 3089.44,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEthcmFtYml0IHwgTWFyYmxlIEZhZGUgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.025,
    },
    {
      id: 'tk-m9-auto',
      weapon: '★ M9 Bayonet',
      skin: 'Autotronic',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 2309.97,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE05IEJheW9uZXQgfCBBdXRvdHJvbmljIChNaW5pbWFsIFdlYXIp.png',
      odds: 0.030,
    },
    {
      id: 'tk-bfk-uv',
      weapon: '★ Butterfly Knife',
      skin: 'Ultraviolet',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 2043.33,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEJ1dHRlcmZseSBLbmlmZSB8IFVsdHJhdmlvbGV0IChNaW5pbWFsIFdlYXIp.png',
      odds: 0.030,
    },
    {
      id: 'tk-nomad-fade',
      weapon: '★ Nomad Knife',
      skin: 'Fade',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 1171.56,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE5vbWFkIEtuaWZlIHwgRmFkZSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.050,
    },
    {
      id: 'tk-stiletto-fade',
      weapon: '★ Stiletto Knife',
      skin: 'Fade',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 1168.49,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFN0aWxldHRvIEtuaWZlIHwgRmFkZSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.050,
    },
    {
      id: 'tk-falchion-gamma',
      weapon: '★ Falchion Knife',
      skin: 'Gamma Doppler',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 607.48,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEZhbGNoaW9uIEtuaWZlIHwgR2FtbWEgRG9wcGxlciAoRmFjdG9yeSBOZXcp.png',
      odds: 0.100,
    },
    {
      id: 'tk-falchion-marble',
      weapon: '★ Falchion Knife',
      skin: 'Marble Fade',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 460.24,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEZhbGNoaW9uIEtuaWZlIHwgTWFyYmxlIEZhZGUgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.200,
    },
    {
      id: 'tk-falchion-tiger',
      weapon: '★ Falchion Knife',
      skin: 'Tiger Tooth',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 376.55,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEZhbGNoaW9uIEtuaWZlIHwgVGlnZXIgVG9vdGggKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.250,
    },
    {
      id: 'tk-daggers-doppler',
      weapon: '★ Shadow Daggers',
      skin: 'Doppler',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 317.79,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNoYWRvdyBEYWdnZXJzIHwgRG9wcGxlciAoRmFjdG9yeSBOZXcp.png',
      odds: 0.270,
    },
    {
      id: 'tk-bowie-lore',
      weapon: '★ Bowie Knife',
      skin: 'Lore',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 300.82,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEJvd2llIEtuaWZlIHwgTG9yZSAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 0.300,
    },
    {
      id: 'tk-survival-ch',
      weapon: '★ Survival Knife',
      skin: 'Case Hardened',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 233.40,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFN1cnZpdmFsIEtuaWZlIHwgQ2FzZSBIYXJkZW5lZCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 3.661,
    },
    {
      id: 'tk-navaja-ddpat',
      weapon: '★ Navaja Knife',
      skin: 'Forest DDPAT',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 112.33,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE5hdmFqYSBLbmlmZSB8IEZvcmVzdCBERFBBVCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 5.000,
    },
    {
      id: 'tk-tec9-army',
      weapon: 'Tec-9',
      skin: 'Army Mesh',
      rarity: 'Consumer',
      condition: 'BS',
      statTrak: false,
      price: 0.05,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/VGVjLTkgfCBBcm15IE1lc2ggKEJhdHRsZS1TY2FycmVkKQ==.png',
      odds: 90.000,
    },
  ],
};