import { CSGOCase } from '../../../../types';

export const tenPercentAKCase: CSGOCase = {
  id: 'ten-percent-ak',
  name: '10% AK',
  price: 35.06,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250815/814831140346052608.png',
  category: 'Official',
  items: [
    {
      id: 'tak-gold-arabesque-fn',
      weapon: 'AK-47',
      skin: 'Gold Arabesque',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 7048.57,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBHb2xkIEFyYWJlc3F1ZSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.003,
    },
    {
      id: 'tak-fire-serpent-fn',
      weapon: 'AK-47',
      skin: 'Fire Serpent',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 4174.22,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBGaXJlIFNlcnBlbnQgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.004,
    },
    {
      id: 'tak-hydroponic-fn',
      weapon: 'AK-47',
      skin: 'Hydroponic',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 6504.95,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBIeWRyb3BvbmljIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.013,
    },
    {
      id: 'tak-xray-fn',
      weapon: 'AK-47',
      skin: 'X-Ray',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 4358.81,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBYLVJheSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.020,
    },
    {
      id: 'tak-monster-fn',
      weapon: 'AK-47',
      skin: 'B the Monster',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 1104.04,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBCIHRoZSBNb25zdGVyIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.030,
    },
    {
      id: 'tak-vulcan-fn',
      weapon: 'AK-47',
      skin: 'Vulcan',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 1292.60,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBWdWxjYW4gKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.040,
    },
    {
      id: 'tak-fuel-injector-fn',
      weapon: 'AK-47',
      skin: 'Fuel Injector',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 937.14,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBGdWVsIEluamVjdG9yIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.050,
    },
    {
      id: 'tak-case-hardened-fn',
      weapon: 'AK-47',
      skin: 'Case Hardened',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 527.97,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBDYXNlIEhhcmRlbmVkIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.070,
    },
    {
      id: 'tak-panthera-fn',
      weapon: 'AK-47',
      skin: 'Panthera onca',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 674.70,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBQYW50aGVyYSBvbmNhIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.170,
    },
    {
      id: 'tak-inheritance-fn',
      weapon: 'AK-47',
      skin: 'Inheritance',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 285.78,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBJbmhlcml0YW5jZSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.300,
    },
    {
      id: 'tak-bloodsport-fn',
      weapon: 'AK-47',
      skin: 'Bloodsport',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 429.75,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBCbG9vZHNwb3J0IChGYWN0b3J5IE5ldyk=.png',
      odds: 0.400,
    },
    {
      id: 'tak-asiimov-fn',
      weapon: 'AK-47',
      skin: 'Asiimov',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 365.69,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBBc2lpbW92IChGYWN0b3J5IE5ldyk=.png',
      odds: 0.400,
    },
    {
      id: 'tak-redline-mw',
      weapon: 'AK-47',
      skin: 'Redline',
      rarity: 'Classified',
      condition: 'MW',
      statTrak: false,
      price: 366.72,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBSZWRsaW5lIChNaW5pbWFsIFdlYXIp.png',
      odds: 0.500,
    },
    {
      id: 'tak-neon-rider-fn',
      weapon: 'AK-47',
      skin: 'Neon Rider',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 336.02,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBOZW9uIFJpZGVyIChGYWN0b3J5IE5ldyk=.png',
      odds: 1.000,
    },
    {
      id: 'tak-aquamarine-fn',
      weapon: 'AK-47',
      skin: 'Aquamarine Revenge',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 336.84,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBBcXVhbWFyaW5lIFJldmVuZ2UgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 2.000,
    },
    {
      id: 'tak-red-laminate-mw',
      weapon: 'AK-47',
      skin: 'Red Laminate',
      rarity: 'Classified',
      condition: 'MW',
      statTrak: false,
      price: 152.46,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBSZWQgTGFtaW5hdGUgKE1pbmltYWwgV2Vhcik=.png',
      odds: 2.000,
    },
    {
      id: 'tak-neon-revolution-fn',
      weapon: 'AK-47',
      skin: 'Neon Revolution',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 251.71,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBOZW9uIFJldm9sdXRpb24gKEZhY3RvcnkgTmV3KQ==.png',
      odds: 3.000,
    },
    {
      id: 'tak-safari-mesh-ft',
      weapon: 'AK-47',
      skin: 'Safari Mesh',
      rarity: 'Consumer',
      condition: 'FT',
      statTrak: false,
      price: 0.07,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBTYWZhcmkgTWVzaCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 90.000,
    },
  ],
};