import { CSGOCase } from '../../../../types';

export const tenPercentM4A1Case: CSGOCase = {
  id: 'ten-percent-m4a1',
  name: '10% M4A1',
  price: 17.22,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250815/814831340892504064.png',
  category: 'Official',
  items: [
    {
      id: 'tm4a1-jungle-fn',
      weapon: 'M4A1-S',
      skin: 'Welcome to the Jungle',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 3969.78,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgV2VsY29tZSB0byB0aGUgSnVuZ2xlIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.003,
    },
    {
      id: 'tm4a1-danger-fn',
      weapon: 'M4A1-S',
      skin: 'Imminent Danger',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 2840.19,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgSW1taW5lbnQgRGFuZ2VyIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.004,
    },
    {
      id: 'tm4a1-hotrod-fn',
      weapon: 'M4A1-S',
      skin: 'Hot Rod',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 3474.77,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgSG90IFJvZCAoRmFjdG9yeSBOZXcp.png',
      odds: 0.013,
    },
    {
      id: 'tm4a1-phosphor-fn',
      weapon: 'M4A1-S',
      skin: 'Blue Phosphor',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 1309.39,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgQmx1ZSBQaG9zcGhvciAoRmFjdG9yeSBOZXcp.png',
      odds: 0.020,
    },
    {
      id: 'tm4a1-masterpiece-fn',
      weapon: 'M4A1-S',
      skin: 'Master Piece',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 562.56,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgTWFzdGVyIFBpZWNlIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.030,
    },
    {
      id: 'tm4a1-printstream-fn',
      weapon: 'M4A1-S',
      skin: 'Printstream',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 1116.82,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgUHJpbnRzdHJlYW0gKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.040,
    },
    {
      id: 'tm4a1-fade-fn',
      weapon: 'M4A1-S',
      skin: 'Fade',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 643.59,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgRmFkZSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.050,
    },
    {
      id: 'tm4a1-vaporwave-fn',
      weapon: 'M4A1-S',
      skin: 'Vaporwave',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 296.01,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgVmFwb3J3YXZlIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.070,
    },
    {
      id: 'tm4a1-chantico-fn',
      weapon: 'M4A1-S',
      skin: "Chantico's Fire",
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 364.70,
      imageUrl: "https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgQ2hhbnRpY28ncyBGaXJlIChGYWN0b3J5IE5ldyk=.png",
      odds: 0.170,
    },
    {
      id: 'tm4a1-hyperbeast-fn',
      weapon: 'M4A1-S',
      skin: 'Hyper Beast',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 324.77,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgSHlwZXIgQmVhc3QgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.300,
    },
    {
      id: 'tm4a1-goldencoil-mw',
      weapon: 'M4A1-S',
      skin: 'Golden Coil',
      rarity: 'Classified',
      condition: 'MW',
      statTrak: false,
      price: 152.32,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgR29sZGVuIENvaWwgKE1pbmltYWwgV2Vhcik=.png',
      odds: 0.400,
    },
    {
      id: 'tm4a1-playertwo-fn',
      weapon: 'M4A1-S',
      skin: 'Player Two',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 264.81,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgUGxheWVyIFR3byAoRmFjdG9yeSBOZXcp.png',
      odds: 0.400,
    },
    {
      id: 'tm4a1-mecha-fn',
      weapon: 'M4A1-S',
      skin: 'Mecha Industries',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 274.92,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgTWVjaGEgSW5kdXN0cmllcyAoRmFjdG9yeSBOZXcp.png',
      odds: 0.500,
    },
    {
      id: 'tm4a1-atomic-fn',
      weapon: 'M4A1-S',
      skin: 'Atomic Alloy',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 189.68,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgQXRvbWljIEFsbG95IChGYWN0b3J5IE5ldyk=.png',
      odds: 1.000,
    },
    {
      id: 'tm4a1-nightmare-fn',
      weapon: 'M4A1-S',
      skin: 'Nightmare',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 102.32,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgTmlnaHRtYXJlIChGYWN0b3J5IE5ldyk=.png',
      odds: 2.000,
    },
    {
      id: 'tm4a1-controlpanel-fn',
      weapon: 'M4A1-S',
      skin: 'Control Panel',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 102.93,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgQ29udHJvbCBQYW5lbCAoRmFjdG9yeSBOZXcp.png',
      odds: 2.000,
    },
    {
      id: 'tm4a1-guardian-fn',
      weapon: 'M4A1-S',
      skin: 'Guardian',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 89.54,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgR3VhcmRpYW4gKEZhY3RvcnkgTmV3KQ==.png',
      odds: 3.000,
    },
    {
      id: 'tm4a1-washme-bs',
      weapon: 'M4A1-S',
      skin: 'Wash me plz',
      rarity: 'Consumer',
      condition: 'BS',
      statTrak: false,
      price: 0.10,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgV2FzaCBtZSBwbHogKEJhdHRsZS1TY2FycmVkKQ==.png',
      odds: 90.000,
    },
  ],
};