import { CSGOCase } from '../../../../types';

export const tenPercentAWPCase: CSGOCase = {
  id: 'ten-percent-awp',
  name: '10% AWP',
  price: 17.81,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250815/814831491329605632.png',
  category: 'Official',
  items: [
    {
      id: 'tawp-prince-fn',
      weapon: 'AWP',
      skin: 'The Prince',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 5573.14,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgVGhlIFByaW5jZSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.003,
    },
    {
      id: 'tawp-hydra-fn',
      weapon: 'AWP',
      skin: 'Desert Hydra',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 4522.52,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgRGVzZXJ0IEh5ZHJhIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.004,
    },
    {
      id: 'tawp-medusa-ft',
      weapon: 'AWP',
      skin: 'Medusa',
      rarity: 'Covert',
      condition: 'FT',
      statTrak: false,
      price: 3161.44,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgTWVkdXNhIChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.013,
    },
    {
      id: 'tawp-fade-fn',
      weapon: 'AWP',
      skin: 'Fade',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 1389.51,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgRmFkZSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.020,
    },
    {
      id: 'tawp-cmyk-fn',
      weapon: 'AWP',
      skin: 'CMYK',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 914.75,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgQ01ZSyAoRmFjdG9yeSBOZXcp.png',
      odds: 0.030,
    },
    {
      id: 'tawp-lightning-fn',
      weapon: 'AWP',
      skin: 'Lightning Strike',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 842.09,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgTGlnaHRuaW5nIFN0cmlrZSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.040,
    },
    {
      id: 'tawp-boom-fn',
      weapon: 'AWP',
      skin: 'BOOM',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 573.00,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgQk9PTSAoRmFjdG9yeSBOZXcp.png',
      odds: 0.050,
    },
    {
      id: 'tawp-oni-fn',
      weapon: 'AWP',
      skin: 'Oni Taiji',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 738.65,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgT25pIFRhaWppIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.070,
    },
    {
      id: 'tawp-containment-fn',
      weapon: 'AWP',
      skin: 'Containment Breach',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 648.01,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgQ29udGFpbm1lbnQgQnJlYWNoIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.170,
    },
    {
      id: 'tawp-silktiger-fn',
      weapon: 'AWP',
      skin: 'Silk Tiger',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 599.50,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgU2lsayBUaWdlciAoRmFjdG9yeSBOZXcp.png',
      odds: 0.300,
    },
    {
      id: 'tawp-crakow-fn',
      weapon: 'AWP',
      skin: 'Crakow!',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 212.73,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgQ3Jha293ISAoRmFjdG9yeSBOZXcp.png',
      odds: 0.400,
    },
    {
      id: 'tawp-asiimov-ft',
      weapon: 'AWP',
      skin: 'Asiimov',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 189.38,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgQXNpaW1vdiAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.400,
    },
    {
      id: 'tawp-graphite-fn',
      weapon: 'AWP',
      skin: 'Graphite',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 250.69,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgR3JhcGhpdGUgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.500,
    },
    {
      id: 'tawp-redline-mw',
      weapon: 'AWP',
      skin: 'Redline',
      rarity: 'Classified',
      condition: 'MW',
      statTrak: false,
      price: 147.24,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgUmVkbGluZSAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 1.000,
    },
    {
      id: 'tawp-wildfire-mw',
      weapon: 'AWP',
      skin: 'Wildfire',
      rarity: 'Classified',
      condition: 'MW',
      statTrak: false,
      price: 112.54,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgV2lsZGZpcmUgKE1pbmltYWwgV2Vhcik=.png',
      odds: 2.000,
    },
    {
      id: 'tawp-sunleo-fn',
      weapon: 'AWP',
      skin: 'Sun in Leo',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 77.32,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgU3VuIGluIExlbyAoRmFjdG9yeSBOZXcp.png',
      odds: 2.000,
    },
    {
      id: 'tawp-noir-fn',
      weapon: 'AWP',
      skin: 'Neo-Noir',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 79.56,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgTmVvLU5vaXIgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 3.000,
    },
    {
      id: 'tawp-safari-ww',
      weapon: 'AWP',
      skin: 'Safari Mesh',
      rarity: 'Consumer',
      condition: 'WW',
      statTrak: false,
      price: 0.18,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QVdQIHwgU2FmYXJpIE1lc2ggKFdlbGwtV29ybik=.png',
      odds: 90.000,
    },
  ],
};
