import { CSGOCase } from '../../../../types';

export const tenPercentM4A4Case: CSGOCase = {
  id: 'ten-percent-m4a4',
  name: '10% M4A4',
  price: 12.10,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250815/814831418487128064.png',
  category: 'Official',
  items: [
    {
      id: 'tm4-howl-fn',
      weapon: 'M4A4',
      skin: 'Howl',
      rarity: 'Contraband',
      condition: 'FN',
      statTrak: false,
      price: 11368.71,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IEhvd2wgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.003,
    },
    {
      id: 'tm4-poseidon-fn',
      weapon: 'M4A4',
      skin: 'Poseidon',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 3304.93,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IFBvc2VpZG9uIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.004,
    },
    {
      id: 'tm4-horus-fn',
      weapon: 'M4A4',
      skin: 'Eye of Horus',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 956.49,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IEV5ZSBvZiBIb3J1cyAoRmFjdG9yeSBOZXcp.png',
      odds: 0.013,
    },
    {
      id: 'tm4-daybreak-fn',
      weapon: 'M4A4',
      skin: 'Daybreak',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 882.25,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IERheWJyZWFrIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.020,
    },
    {
      id: 'tm4-coalition-fn',
      weapon: 'M4A4',
      skin: 'The Coalition',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 849.25,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IFRoZSBDb2FsaXRpb24gKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.030,
    },
    {
      id: 'tm4-asiimov-ft',
      weapon: 'M4A4',
      skin: 'Asiimov',
      rarity: 'Covert',
      condition: 'FT',
      statTrak: false,
      price: 284.34,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IEFzaWltb3YgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 0.040,
    },
    {
      id: 'tm4-emperor-fn',
      weapon: 'M4A4',
      skin: 'The Emperor',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 337.65,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IFRoZSBFbXBlcm9yIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.050,
    },
    {
      id: 'tm4-temukau-fn',
      weapon: 'M4A4',
      skin: 'Temukau',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 157.17,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IFRlbXVrYXUgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.070,
    },
    {
      id: 'tm4-bulletrain-fn',
      weapon: 'M4A4',
      skin: 'Bullet Rain',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 384.11,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IEJ1bGxldCBSYWluIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.170,
    },
    {
      id: 'tm4-hellfire-fn',
      weapon: 'M4A4',
      skin: 'Hellfire',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 238.73,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IEhlbGxmaXJlIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.300,
    },
    {
      id: 'tm4-cyber-fn',
      weapon: 'M4A4',
      skin: 'Cyber Security',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 170.22,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IEN5YmVyIFNlY3VyaXR5IChGYWN0b3J5IE5ldyk=.png',
      odds: 0.400,
    },
    {
      id: 'tm4-noir-fn',
      weapon: 'M4A4',
      skin: 'Neo-Noir',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 130.13,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IE5lby1Ob2lyIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.400,
    },
    {
      id: 'tm4-incolor-fn',
      weapon: 'M4A4',
      skin: 'In Living Color',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 123.81,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IEluIExpdmluZyBDb2xvciAoRmFjdG9yeSBOZXcp.png',
      odds: 0.500,
    },
    {
      id: 'tm4-dragonking-fn',
      weapon: 'M4A4',
      skin: '龍王 (Dragon King)',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 94.06,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IOm=jeeOiyAoRHJhZ29uIEtpbmcpIChGYWN0b3J5IE5ldyk=.png',
      odds: 1.000,
    },
    {
      id: 'tm4-radiation-ft',
      weapon: 'M4A4',
      skin: 'Radiation Hazard',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 42.16,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IFJhZGlhdGlvbiBIYXphcmQgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 2.000,
    },
    {
      id: 'tm4-desolate-fn',
      weapon: 'M4A4',
      skin: 'Desolate Space',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 97.54,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IERlc29sYXRlIFNwYWNlIChGYWN0b3J5IE5ldyk=.png',
      odds: 2.000,
    },
    {
      id: 'tm4-spiderlily-fn',
      weapon: 'M4A4',
      skin: 'Spider Lily',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 82.25,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IFNwaWRlciBMaWx5IChGYWN0b3J5IE5ldyk=.png',
      odds: 3.000,
    },
    {
      id: 'tm4-mainframe-mw',
      weapon: 'M4A4',
      skin: 'Mainframe',
      rarity: 'Mil-Spec',
      condition: 'MW',
      statTrak: false,
      price: 0.09,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IE1haW5mcmFtZSAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 90.000,
    },
  ],
};
