import { CSGOCase } from '../../../../types';

export const tenPercentPistolCase: CSGOCase = {
  id: 'ten-percent-pistol',
  name: '10% Pistol',
  price: 2.29,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250815/814870382686289920.png',
  category: 'Official',
  items: [
    {
      id: 'tp-01',
      weapon: 'Desert Eagle',
      skin: 'Blaze',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 1172.59,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RGVzZXJ0IEVhZ2xlIHwgQmxhemUgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.010,
    },
    {
      id: 'tp-02',
      weapon: 'Desert Eagle',
      skin: 'Sunset Storm 弐',
      rarity: 'Extraordinary',
      condition: 'FN',
      statTrak: false,
      price: 810.37,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RGVzZXJ0IEVhZ2xlIHwgU3Vuc2V0IFN0b3JtIOW8kCAoRmFjdG9yeSBOZXcp.png',
      odds: 0.020,
    },
    {
      id: 'tp-03',
      weapon: 'Souvenir Desert Eagle',
      skin: 'Fennec Fox',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 257.54,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U291dmVuaXIgRGVzZXJ0IEVhZ2xlIHwgRmVubmVjIEZveCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.070,
    },
    {
      id: 'tp-04',
      weapon: 'USP-S',
      skin: 'Kill Confirmed',
      rarity: 'Covert',
      condition: 'FT',
      statTrak: false,
      price: 81.42,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/VVNQLVMgfCBLaWxsIENvbmZpcm1lZCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.100,
    },
    {
      id: 'tp-05',
      weapon: 'P2000',
      skin: 'Ocean Foam',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 195.23,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/UDIwMDAgfCBPY2VhbiBGb2FtIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.200,
    },
    {
      id: 'tp-06',
      weapon: 'Five-SeveN',
      skin: 'Berries And Cherries',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 167.61,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/Rml2ZS1TZXZlTiB8IEJlcnJpZXMgQW5kIENoZXJyaWVzIChGYWN0b3J5IE5ldyk=.png',
      odds: 0.200,
    },
    {
      id: 'tp-07',
      weapon: 'Glock-18',
      skin: 'Shinobu',
      rarity: 'Classified',
      condition: 'FN',
      statTrak: false,
      price: 29.99,
      imageUrl: 'https://csgo-oss.funcs2.com/e//steam/item/730/R2xvY2stMTggfCBTaGlub2J1IChGYWN0b3J5IE5ldyk=.png',
      odds: 0.400,
    },
    {
      id: 'tp-08',
      weapon: 'Desert Eagle',
      skin: 'Serpent Strike',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 2.96,
      imageUrl: 'https://csgo-oss.funcs2.com/e//steam/item/730/RGVzZXJ0IEVhZ2xlIHwgU2VycGVudCBTdHJpa2UgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 3.000,
    },
    {
      id: 'tp-09',
      weapon: 'Desert Eagle',
      skin: 'Blue Ply',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 2.80,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RGVzZXJ0IEVhZ2xlIHwgQmx1ZSBQbHkgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 6.000,
    },
    {
      id: 'tp-10',
      weapon: 'Glock-18',
      skin: 'Clear Polymer',
      rarity: 'Mil-Spec',
      condition: 'MW',
      statTrak: false,
      price: 0.47,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/R2xvY2stMTggfCBDbGVhciBQb2x5bWVyIChNaW5pbWFsIFdlYXIp.png',
      odds: 90.000,
    },
  ],
};
