import { CSGOCase } from '../../../../types';

export const tenPercentGlovesCase: CSGOCase = {
  id: 'ten-percent-gloves',
  name: '10% Gloves',
  price: 15.24,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250815/814831012260397057.png',
  category: 'Official',
  items: [
    {
      id: 'tg-gloves-vice-mw',
      weapon: '★ Sport Gloves',
      skin: 'Vice',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 6007.81,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IFZpY2UgKE1pbmltYWwgV2Vhcik=.png',
      odds: 0.003,
    },
    {
      id: 'tg-gloves-spearmint-ft',
      weapon: '★ Moto Gloves',
      skin: 'Spearmint',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 5729.89,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE1vdG8gR2xvdmVzIHwgU3BlYXJtaW50IChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.004,
    },
    {
      id: 'tg-gloves-kimono-bs',
      weapon: '★ Specialist Gloves',
      skin: 'Crimson Kimono',
      rarity: 'Extraordinary',
      condition: 'BS',
      statTrak: false,
      price: 2901.78,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwZWNpYWxpc3QgR2xvdmVzIHwgQ3JpbXNvbiBLaW1vbm8gKEJhdHRsZS1TY2FycmVkKQ==.png',
      odds: 0.013,
    },
    {
      id: 'tg-gloves-leopard-mw',
      weapon: '★ Driver Gloves',
      skin: 'Snow Leopard',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 1777.80,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIERyaXZlciBHbG92ZXMgfCBTbm93IExlb3BhcmQgKE1pbmltYWwgV2Vhcik=.png',
      odds: 0.020,
    },
    {
      id: 'tg-gloves-amphibious-ft',
      weapon: '★ Sport Gloves',
      skin: 'Amphibious',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 1109.86,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IEFtcGhpYmlvdXMgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 0.030,
    },
    {
      id: 'tg-gloves-omega-ft',
      weapon: '★ Sport Gloves',
      skin: 'Omega',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 656.80,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IE9tZWdhIChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.040,
    },
    {
      id: 'tg-gloves-plaid-ft',
      weapon: '★ Driver Gloves',
      skin: 'Imperial Plaid',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 561.83,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIERyaXZlciBHbG92ZXMgfCBJbXBlcmlhbCBQbGFpZCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.050,
    },
    {
      id: 'tg-gloves-kingsnake-ft',
      weapon: '★ Driver Gloves',
      skin: 'King Snake',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 478.31,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIERyaXZlciBHbG92ZXMgfCBLaW5nIFNuYWtlIChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.070,
    },
    {
      id: 'tg-gloves-turtle-mw',
      weapon: '★ Moto Gloves',
      skin: 'Turtle',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 518.36,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE1vdG8gR2xvdmVzIHwgVHVydGxlIChNaW5pbWFsIFdlYXIp.png',
      odds: 0.170,
    },
    {
      id: 'tg-gloves-pow-ft',
      weapon: '★ Moto Gloves',
      skin: 'POW!',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 316.99,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE1vdG8gR2xvdmVzIHwgUE9XISAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.300,
    },
    {
      id: 'tg-gloves-rezan-ft',
      weapon: '★ Driver Gloves',
      skin: 'Rezan the Red',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 253.34,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIERyaXZlciBHbG92ZXMgfCBSZXphbiB0aGUgUmVkIChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.400,
    },
    {
      id: 'tg-gloves-bronze-bs',
      weapon: '★ Sport Gloves',
      skin: 'Bronze Morph',
      rarity: 'Extraordinary',
      condition: 'BS',
      statTrak: false,
      price: 239.23,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IEJyb256ZSBNb3JwaCAoQmF0dGxlLVNjYXJyZWQp.png',
      odds: 0.400,
    },
    {
      id: 'tg-gloves-buckshot-bs',
      weapon: '★ Specialist Gloves',
      skin: 'Buckshot',
      rarity: 'Extraordinary',
      condition: 'BS',
      statTrak: false,
      price: 119.72,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwZWNpYWxpc3QgR2xvdmVzIHwgQnVja3Nob3QgKEJhdHRsZS1TY2FycmVkKQ==.png',
      odds: 0.500,
    },
    {
      id: 'tg-gloves-transport-ft',
      weapon: '★ Moto Gloves',
      skin: 'Transport',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 111.94,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE1vdG8gR2xvdmVzIHwgVHJhbnNwb3J0IChGaWVsZC1UZXN0ZWQp.png',
      odds: 1.000,
    },
    {
      id: 'tg-gloves-mangrove-ft',
      weapon: '★ Hydra Gloves',
      skin: 'Mangrove',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 81.84,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEh5ZHJhIEdsb3ZlcyB8IE1hbmdyb3ZlIChGaWVsZC1UZXN0ZWQp.png',
      odds: 2.000,
    },
    {
      id: 'tg-gloves-rattler-ft',
      weapon: '★ Hydra Gloves',
      skin: 'Rattler',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 83.90,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEh5ZHJhIEdsb3ZlcyB8IFJhdHRsZXIgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 2.000,
    },
    {
      id: 'tg-gloves-racinggreen-ft',
      weapon: '★ Driver Gloves',
      skin: 'Racing Green',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 83.40,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIERyaXZlciBHbG92ZXMgfCBSYWNpbmcgR3JlZW4gKEZpZWxkLVRlc3RlZCk=.png',
      odds: 3.000,
    },
    {
      id: 'tg-scar20-contractor-bs',
      weapon: 'SCAR-20',
      skin: 'Contractor',
      rarity: 'Consumer',
      condition: 'BS',
      statTrak: false,
      price: 0.03,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U0NBUi0yMCB8IENvbnRyYWN0b3IgKEJhdHRsZS1TY2FycmVkKQ==.png',
      odds: 90.000,
    },
  ],
};
