import { CSGOCase } from '../../../../types';

export const ultravioletCase: CSGOCase = {
  id: 'ultraviolet',
  name: 'Ultraviolet',
  price: 26.48,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250811/813434499097452544.png',
  category: 'Official',
  items: [
    {
      id: 'uv-karambit-bs',
      weapon: '★ Karambit',
      skin: 'Ultraviolet',
      rarity: 'Extraordinary',
      condition: 'BS',
      statTrak: false,
      price: 1159.59,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEthcmFtYml0IHwgVWx0cmF2aW9sZXQgKEJhdHRsZS1TY2FycmVkKQ==.png',
      odds: 0.200,
      groupId: 'uv-karambit',
    },
    {
      id: 'uv-stiletto-ft',
      weapon: '★ Stiletto Knife',
      skin: 'Ultraviolet',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 403.92,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFN0aWxldHRvIEtuaWZlIHwgVWx0cmF2aW9sZXQgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 0.600,
      groupId: 'uv-stiletto',
    },
    {
      id: 'uv-bayonet-ft',
      weapon: '★ Bayonet',
      skin: 'Ultraviolet',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 317.17,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEJheW9uZXQgfCBVbHRyYXZpb2xldCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.700,
      groupId: 'uv-bayonet',
    },
    {
      id: 'uv-gut-ft',
      weapon: '★ Gut Knife',
      skin: 'Ultraviolet',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 155.30,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIEd1dCBLbmlmZSB8IFVsdHJhdmlvbGV0IChGaWVsZC1UZXN0ZWQp.png',
      odds: 1.000,
      groupId: 'uv-gut',
    },
    {
      id: 'uv-daggers-ft',
      weapon: '★ Shadow Daggers',
      skin: 'Ultraviolet',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 143.26,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNoYWRvdyBEYWdnZXJzIHwgVWx0cmF2aW9sZXQgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 1.100,
      groupId: 'uv-daggers',
    },
    {
      id: 'uv-navaja-ft',
      weapon: '★ Navaja Knife',
      skin: 'Ultraviolet',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 124.63,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE5hdmFqYSBLbmlmZSB8IFVsdHJhdmlvbGV0IChGaWVsZC1UZXN0ZWQp.png',
      odds: 1.200,
      groupId: 'uv-navaja',
    },
    {
      id: 'uv-m4a1s-decimator-ft',
      weapon: 'M4A1-S',
      skin: 'Decimator',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 19.20,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgRGVjaW1hdG9yIChGaWVsZC1UZXN0ZWQp.png',
      odds: 10.000,
      groupId: 'uv-decimator',
    },
    {
      id: 'uv-ssg08-turbo-ft',
      weapon: 'SSG 08',
      skin: 'Turbo Peek',
      rarity: 'Restricted',
      condition: 'FT',
      statTrak: false,
      price: 15.50,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U1NHIDA4IHwgVHVyYm8gUGVlayAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 11.000,
      groupId: 'uv-turbo-peek',
    },
    {
      id: 'uv-mac10-disco-mw',
      weapon: 'MAC-10',
      skin: 'Disco Tech',
      rarity: 'Classified',
      condition: 'MW',
      statTrak: false,
      price: 7.89,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TUFDLTEwIHwgRGlzY28gVGVjaCAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 12.000,
      groupId: 'uv-disco-tech',
    },
    {
      id: 'uv-galil-chromatic-mw',
      weapon: 'Galil AR',
      skin: 'Chromatic Aberration',
      rarity: 'Restricted',
      condition: 'MW',
      statTrak: false,
      price: 6.75,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/R2FsaWwgQVIgfCBDaHJvbWF0aWMgQWJlcnJhdGlvbiAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 13.500,
      groupId: 'uv-chromatic',
    },
    {
      id: 'uv-glock-moonrise-mw-st',
      weapon: 'StatTrak™ Glock-18',
      skin: 'Moonrise',
      rarity: 'Restricted',
      condition: 'MW',
      statTrak: true,
      price: 3.48,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U3RhdFRyYWvihKIgR2xvY2stMTggfCBNb29ucmlzZSAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 15.000,
      groupId: 'uv-moonrise',
    },
    {
      id: 'uv-mac10-ultraviolet-ft',
      weapon: 'MAC-10',
      skin: 'Ultraviolet',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 3.33,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TUFDLTEwIHwgVWx0cmF2aW9sZXQgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 16.000,
      groupId: 'uv-mac10-ultraviolet',
    },
    {
      id: 'uv-sg553-ultraviolet-mw',
      weapon: 'SG 553',
      skin: 'Ultraviolet',
      rarity: 'Mil-Spec',
      condition: 'MW',
      statTrak: false,
      price: 30.56,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U0cgNTUzIHwgVWx0cmF2aW9sZXQgKE1pbmltYWwgV2Vhcik=.png',
      odds: 6.000,
      groupId: 'uv-sg553-ultraviolet',
    },
    {
      id: 'uv-sg553-ultraviolet-ft',
      weapon: 'SG 553',
      skin: 'Ultraviolet',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 30.00,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U0cgNTUzIHwgVWx0cmF2aW9sZXQgKE1pbmltYWwgV2Vhcik=.png',
      odds: 11.700,
      groupId: 'uv-sg553-ultraviolet',
    },
  ],
};
