import { CSGOCase } from '../../../../types';

export const wasdCase: CSGOCase = {
  id: 'wasd',
  name: 'WASD',
  price: 6.35,
  imageUrl: 'https://csgo-oss.funcs2.com/uploadfile/20250731/809525518834618368.png',
  category: 'Creators',
  items: [
    {
      id: 'wasd-ak-fuel',
      weapon: 'AK-47',
      skin: 'Fuel Injector',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: false,
      price: 437.22,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBGdWVsIEluamVjdG9yIChNaW5pbWFsIFdlYXIp.png',
      odds: 0.030,
    },
    {
      id: 'wasd-gloves-bronze',
      weapon: '★ Sport Gloves',
      skin: 'Bronze Morph',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 296.63,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNwb3J0IEdsb3ZlcyB8IEJyb256ZSBNb3JwaCAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 0.070,
    },
    {
      id: 'wasd-deagle-ocean',
      weapon: 'Desert Eagle',
      skin: 'Ocean Drive',
      rarity: 'Covert',
      condition: 'FN',
      statTrak: false,
      price: 302.26,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RGVzZXJ0IEVhZ2xlIHwgT2NlYW4gRHJpdmUgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 0.080,
    },
    {
      id: 'wasd-daggers-auto',
      weapon: '★ Shadow Daggers',
      skin: 'Autotronic',
      rarity: 'Extraordinary',
      condition: 'MW',
      statTrak: false,
      price: 181.73,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIFNoYWRvdyBEYWdnZXJzIHwgQXV0b3Ryb25pYyAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 0.100,
    },
    {
      id: 'wasd-navaja-crimson',
      weapon: '★ Navaja Knife',
      skin: 'Crimson Web',
      rarity: 'Extraordinary',
      condition: 'FT',
      statTrak: false,
      price: 153.08,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/4piFIE5hdmFqYSBLbmlmZSB8IENyaW1zb24gV2ViIChGaWVsZC1UZXN0ZWQp.png',
      odds: 0.110,
    },
    {
      id: 'wasd-ak-neon',
      weapon: 'AK-47',
      skin: 'Neon Rider',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: false,
      price: 121.52,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBOZW9uIFJpZGVyIChNaW5pbWFsIFdlYXIp.png',
      odds: 0.150,
    },
    {
      id: 'wasd-st-m4-bullet',
      weapon: 'M4A4',
      skin: 'Bullet Rain',
      rarity: 'Covert',
      condition: 'MW',
      statTrak: true,
      price: 132.24,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U3RhdFRyYWvihKIgTTRBNCB8IEJ1bGxldCBSYWluIChNaW5pbWFsIFdlYXIp.png',
      odds: 0.160,
    },
    {
      id: 'wasd-st-ssg-turbo',
      weapon: 'SSG 08',
      skin: 'Turbo Peek',
      rarity: 'Restricted',
      condition: 'MW',
      statTrak: true,
      price: 56.21,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/U3RhdFRyYWvihKIgU1NHIDA4IHwgVHVyYm8gUGVlayAoTWluaW1hbCBXZWFyKQ==.png',
      odds: 0.400,
    },
    {
      id: 'wasd-m4a1s-glitch',
      weapon: 'M4A1-S',
      skin: 'Glitched Paint',
      rarity: 'Classified',
      condition: 'MW',
      statTrak: false,
      price: 27.01,
      imageUrl: 'https://csgo-oss.funcs2.com/e//steam/item/730/TTRBMS1TIHwgR2xpdGNoZWQgUGFpbnQgKE1pbmltYWwgV2Vhcik=.png',
      odds: 0.600,
    },
    {
      id: 'wasd-m4a1s-hyper',
      weapon: 'M4A1-S',
      skin: 'Hyper Beast',
      rarity: 'Covert',
      condition: 'FT',
      statTrak: false,
      price: 34.78,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBMS1TIHwgSHlwZXIgQmVhc3QgKEZpZWxkLVRlc3RlZCk=.png',
      odds: 0.700,
    },
    {
      id: 'wasd-glock-gold',
      weapon: 'Glock-18',
      skin: 'Gold Toof',
      rarity: 'Classified',
      condition: 'MW',
      statTrak: false,
      price: 29.82,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/R2xvY2stMTggfCBHb2xkIFRvb2YgKE1pbmltYWwgV2Vhcik=.png',
      odds: 0.800,
    },
    {
      id: 'wasd-duals-angels',
      weapon: 'Dual Berettas',
      skin: 'Sweet Little Angels',
      rarity: 'Restricted',
      condition: 'FN',
      statTrak: false,
      price: 18.14,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RHVhbCBCZXJldHRhcyB8IFN3ZWV0IExpdHRsZSBBbmdlbHMgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 1.600,
    },
    {
      id: 'wasd-zeus-olympus',
      weapon: 'Zeus x27',
      skin: 'Olympus',
      rarity: 'Restricted',
      condition: 'MW',
      statTrak: false,
      price: 11.05,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/WmV1cyB4MjcgfCBPbHltcHVzIChNaW5pbWFsIFdlYXIp.png',
      odds: 2.700,
    },
    {
      id: 'wasd-m4-desolate',
      weapon: 'M4A4',
      skin: 'Desolate Space',
      rarity: 'Classified',
      condition: 'FT',
      statTrak: false,
      price: 11.01,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TTRBNCB8IERlc29sYXRlIFNwYWNlIChGaWVsZC1UZXN0ZWQp.png',
      odds: 5.500,
    },
    {
      id: 'wasd-ak-ice',
      weapon: 'AK-47',
      skin: 'Ice Coaled',
      rarity: 'Restricted',
      condition: 'FT',
      statTrak: false,
      price: 4.84,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/QUstNDcgfCBJY2UgQ29hbGVkIChGaWVsZC1UZXN0ZWQp.png',
      odds: 9.500,
    },
    {
      id: 'wasd-bizon-roller',
      weapon: 'PP-Bizon',
      skin: 'High Roller',
      rarity: 'Restricted',
      condition: 'FT',
      statTrak: false,
      price: 3.64,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/UFAtQml6b24gfCBIaWdoIFJvbGxlciAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 12.000,
    },
    {
      id: 'wasd-mp9-food',
      weapon: 'MP9',
      skin: 'Food Chain',
      rarity: 'Mil-Spec',
      condition: 'FT',
      statTrak: false,
      price: 2.59,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/TVA5IHwgRm9vZCBDaGFpbiAoRmllbGQtVGVzdGVkKQ==.png',
      odds: 14.000,
    },
    {
      id: 'wasd-ump-moonrise',
      weapon: 'UMP-45',
      skin: 'Moonrise',
      rarity: 'Mil-Spec',
      condition: 'FN',
      statTrak: false,
      price: 2.11,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/VU1QLTQ1IHwgTW9vbnJpc2UgKEZhY3RvcnkgTmV3KQ==.png',
      odds: 15.500,
    },
    {
      id: 'wasd-deagle-trigger',
      weapon: 'Desert Eagle',
      skin: 'Trigger Discipline',
      rarity: 'Mil-Spec',
      condition: 'MW',
      statTrak: false,
      price: 1.91,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/RGVzZXJ0IEVhZ2xlIHwgVHJpZ2dlciBEaXNjaXBsaW5lIChNaW5pbWFsIFdlYXIp.png',
      odds: 17.200,
    },
    {
      id: 'wasd-p250-franklin',
      weapon: 'P250',
      skin: 'Franklin',
      rarity: 'Classified',
      condition: 'MW',
      statTrak: false,
      price: 2.21,
      imageUrl: 'https://csgo-oss.funcs2.com/e/steam/item/730/UDI1MCB8IEZyYW5rbGluIChNaW5pbWFsIFdlYXIp.png',
      odds: 18.800,
    },
  ],
};